"""Initial schema migration setup

Revision ID: 09771da61373
Revises: 
Create Date: 2026-10-04 22:13:41.856974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '09771da61373'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('traders')
    op.drop_table('products')
    op.drop_table('sales')
    op.drop_table('cash_snapshots')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('credits')
    op.drop_table('price_indices')
    op.drop_table('purchases')
    op.drop_table('transactions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('transaction_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('trader_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('type', postgresql.ENUM('SALE', 'PURCHASE', 'EXPENSE', 'PERSONAL_WITHDRAWAL', 'CREDIT_GIVEN', 'CREDIT_REPAID', name='transaction_type_enum'), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('payment_method', postgresql.ENUM('CASH', 'TELEBIRR', 'CBE_BIRR', 'M_PESA', 'CREDIT', name='payment_method_enum'), autoincrement=False, nullable=True),
    sa.Column('counterparty', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['trader_id'], ['traders.trader_id'], name=op.f('transactions_trader_id_fkey')),
    sa.PrimaryKeyConstraint('transaction_id', name=op.f('transactions_pkey'))
    )
    op.create_table('purchases',
    sa.Column('purchase_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('trader_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('unit_cost_at_purchase', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('supplier', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('purchase_date', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], name=op.f('purchases_product_id_fkey')),
    sa.ForeignKeyConstraint(['trader_id'], ['traders.trader_id'], name=op.f('purchases_trader_id_fkey')),
    sa.PrimaryKeyConstraint('purchase_id', name=op.f('purchases_pkey'))
    )
    op.create_table('price_indices',
    sa.Column('price_index_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('country', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('month', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('index_value', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('price_index_id', name=op.f('price_indices_pkey'))
    )
    op.create_table('credits',
    sa.Column('credit_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('trader_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('customer_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('amount_owed', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('date_given', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('due_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('amount_repaid', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('OPEN', 'PARTIAL', 'CLOSED', name='credit_status_enum'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['trader_id'], ['traders.trader_id'], name=op.f('credits_trader_id_fkey')),
    sa.PrimaryKeyConstraint('credit_id', name=op.f('credits_pkey'))
    )
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('role', postgresql.ENUM('ADMIN', 'TRADER', name='user_role_enum'), autoincrement=False, nullable=False),
    sa.Column('trader_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['trader_id'], ['traders.trader_id'], name=op.f('users_trader_id_fkey')),
    sa.PrimaryKeyConstraint('user_id', name=op.f('users_pkey'))
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('cash_snapshots',
    sa.Column('cash_snapshot_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('trader_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), server_default=sa.text('CURRENT_DATE'), autoincrement=False, nullable=True),
    sa.Column('cash_on_hand', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('mobile_money_balance', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('working_capital', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('true_profit_estimate', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['trader_id'], ['traders.trader_id'], name=op.f('cash_snapshots_trader_id_fkey')),
    sa.PrimaryKeyConstraint('cash_snapshot_id', name=op.f('cash_snapshots_pkey'))
    )
    op.create_table('sales',
    sa.Column('sale_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('transaction_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('quantity_sold', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('unit_sale_price', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('sale_date', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], name=op.f('sales_product_id_fkey')),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.transaction_id'], name=op.f('sales_transaction_id_fkey')),
    sa.PrimaryKeyConstraint('sale_id', name=op.f('sales_pkey'))
    )
    op.create_table('products',
    sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('trader_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('product_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('unit', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('current_stock_quantity', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['trader_id'], ['traders.trader_id'], name=op.f('products_trader_id_fkey')),
    sa.PrimaryKeyConstraint('product_id', name=op.f('products_pkey'))
    )
    op.create_table('traders',
    sa.Column('trader_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('phone_number', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('business_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('region', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('registration_date', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('trader_id', name=op.f('traders_pkey')),
    sa.UniqueConstraint('phone_number', name=op.f('traders_phone_number_key'))
    )
    # ### end Alembic commands ###
